apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: terraform
    environment: ${ENVIRONMENT}
data:
  mapRoles: |
    - rolearn: ${NODE_ROLE}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: ${ADMIN_ROLE}
      username: admin-user
      groups:
        - system:masters
        - eks-admins
    - rolearn: ${DEV_ROLE}
      username: developer-user
      groups:
        - eks-developers
    - rolearn: ${READONLY_ROLE}
      username: readonly-user
      groups:
        - eks-readonly