apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::354852339163:user/EChukwuDevopsLab
      username: admin
      groups:
        - system:masters
