name: "EKS Load Balancer Setup"

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      vpc_id:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  HELM_VERSION: "3.12.3"
  MAX_RETRIES: 3

jobs:
  setup-loadbalancer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Tools
        run: |
          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          
          # Install Helm
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh --version v${HELM_VERSION}
          
          # Install eksctl
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      # Configure kubectl for EKS before other operations
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name ${{ inputs.cluster_name }} \
            --region ${{ env.AWS_REGION }}
          
          # Verify connection
          kubectl get svc

      - name: Configure Load Balancer
        run: |
          eksctl utils associate-iam-oidc-provider \
            --cluster ${{ inputs.cluster_name }} \
            --region ${{ env.AWS_REGION }} \
            --approve

          curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.11.0/docs/install/iam_policy.json
          
          aws iam create-policy \
            --policy-name AWSLoadBalancerControllerIAMPolicy \
            --policy-document file://iam_policy.json || true

          eksctl create iamserviceaccount \
            --cluster=${{ inputs.cluster_name }} \
            --namespace=kube-system \
            --name=aws-load-balancer-controller \
            --role-name AmazonEKSLoadBalancerControllerRole \
            --attach-policy-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy \
            --region ${{ env.AWS_REGION }} \
            --override-existing-serviceaccounts \
            --approve

      - name: Install Controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update eks

          # Add verification step
          kubectl get namespace kube-system || kubectl create namespace kube-system

          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            -n kube-system \
            --set clusterName=${{ inputs.cluster_name }} \
            --set serviceAccount.create=false \
            --set serviceAccount.name=aws-load-balancer-controller \
            --set region=${{ env.AWS_REGION }} \
            --set vpcId=${{ inputs.vpc_id }} \
            --wait \
            --timeout 15m