name: "EKS Application Deployment"

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  K8S_DIR: ./kubernetes
  MAX_RETRIES: 3

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name "${{ inputs.cluster_name }}" \
            --region "${{ env.AWS_REGION }}"

      - name: Deploy Application
        id: deploy
        run: |
          set -e
          
          echo "Deploying application components..."
          
          for manifest in serviceaccount.yaml complete-deploy.yaml frontendproxy/ingress.yaml; do
            if [ ! -f "${{ env.K8S_DIR }}/$manifest" ]; then
              echo "Warning: Manifest file $manifest not found. Skipping..."
              continue
            fi
          
            echo "Applying $manifest..."
            kubectl apply -f "${{ env.K8S_DIR }}/$manifest" || {
              echo "Failed to apply $manifest"
              exit 1
            }
          done
          
          echo "Waiting for deployments to be ready..."
          kubectl wait --for=condition=available deployment --all --timeout=300s

      - name: Verify Deployment
        if: success() || steps.deploy.outcome == 'failure'
        run: |
          echo "Deployment Status:"
          kubectl get deployments -A
          
          echo "Pod Status:"
          kubectl get pods -A
          
          echo "Service Status:"
          kubectl get services -A
          
          echo "Ingress Status:"
          kubectl get ingress -A

      - name: Notify Deployment Failure
        if: failure()
        run: |
          echo "Deployment to ${{ inputs.cluster_name }} failed"
          exit 1