name: "EKS Application Deployment"

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  K8S_DIR: ./kubernetes
  MAX_RETRIES: 3

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install and Configure kubectl
        run: |
          # Get stable kubectl version
          KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          echo "Installing kubectl version: ${KUBECTL_VERSION}"
          
          # Download kubectl
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          
          # Verify download
          if [ ! -f kubectl ]; then
            echo "Failed to download kubectl"
            exit 1
          fi
          
          # Install kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          
          # Verify installation
          if ! command -v kubectl &> /dev/null; then
            echo "kubectl not installed correctly"
            exit 1
          fi
          
          # Configure kubectl for EKS
          echo "Configuring kubectl for cluster: ${{ inputs.cluster_name }}"
          aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region ${{ env.AWS_REGION }}
          
          # Verify cluster access
          kubectl cluster-info

      - name: Deploy Application
        run: |
          echo "Deploying application components..."
          
          echo "Applying service account..."
          kubectl apply -f ${{ env.K8S_DIR }}/serviceaccount.yaml
          
          echo "Applying main deployment..."
          kubectl apply -f ${{ env.K8S_DIR }}/complete-deploy.yaml
          
          echo "Applying ingress..."
          kubectl apply -f ${{ env.K8S_DIR }}/frontendproxy/ingress.yaml
          
          echo "Waiting for deployments to be ready..."
          kubectl wait --for=condition=available deployment --all --timeout=300s

      - name: Verify Deployment
        run: |
          echo "Deployment Status:"
          kubectl get deployments -A
          
          echo "Pod Status:"
          kubectl get pods -A
          
          echo "Service Status:"
          kubectl get services -A
          
          echo "Ingress Status:"
          kubectl get ingress -A